### ISSUE TITLE
Use Lambda Node 6.10 runtime

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-sharp-image#24]
Make necessary updates in babel (use preset-env), webpack (remove this dependency?) to make use of Node 6.10 runtime.

- [x] use babel preset-env and target node 6.10
- [x] compile new sharp-lib for node 6.10

**Comment by manakor** [comment]
Probably, it will also require to update `lib/sharp-0.17.2-linux-x64.tar.gz`? 
So `node_modules/` in there match Nodejs 6.0.

**Comment by adieuadieu** [comment]
@manakor yes you are correct!
