### ISSUE TITLE
"type" (Content-Type) appears to be ignored

### ISSUE THREAD

**Issue by smoll** [adieuadieu/serverless-sharp-image#43]
I noticed that all my transformed images have Content-Type "application/octet-stream" (the default), and then found the mention of `type` in the readme. However, even after setting it, it looks like it's not being respected.

My use case is basically straight from the readme, with a few modifications:

```
    {
      "key": "%(filename)s_200x200.jpg",
      "type": "%(type)s",
      "params": {
        "ACL": "public-read"
      },
      "operations": [
        ["resize", 200, 200],
        ["max"],
        ["crop", "entropy"],
        ["withoutEnlargement"]
      ]
    },
```

even when I hardcode the string `"type": "image/jpeg",`, when I do a HTTP GET on the transformed image, I get `Content-Type: application/octet-stream`

This shouldn't matter, but the original file has `Content-Type: image/jpeg`. Let me know if there's anything else I can do to help with this. I'll try to take a look at the code to see if there's a straightforward fix here.

**Comment by adieuadieu** [comment]
Hi @smoll — It seems that perhaps the documentation is a bit confusing. In the "Available arguments for use in the output object key" section, `type` refers to a placeholder that can be used in the outputs S3 Key. E.g. `{ key: '%(type)s/200x200.jpg' }`.

However, it does seems you have encountered an issue with the Content-Type not being set correctly. I'll push a fix in a bit that will set the Content-Type automatically. In the meantime, you can manually set it by adding `"ContentType": "image/jpeg"` within the `params` section of the configuration, e.g.: 

```json
    {
      "key": "%(filename)s_200x200.jpg",
      "type": "%(type)s",
      "params": {
        "ACL": "public-read",
        "ContentType": "image/jpeg"    <----------------
      },
      "operations": [
        ["resize", 200, 200],
        ["max"],
        ["crop", "entropy"],
        ["withoutEnlargement"]
      ]
    },
```

You can override/set any of the S3 `params` in this section. All of the available S3 params are [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) in the Parameter `params` section.

**Comment by adieuadieu** [comment]
@smoll Content-Type should now be set correctly automatically. 😃
