### ISSUE TITLE
Does not work on eu-central-1

### ISSUE THREAD

**Issue by Christilut** [adieuadieu/serverless-sharp-image#46]
Seems like the script doesn't work if `eu-central-1` is used as region. It will always say the bucket was not found.
Works fine if I switch region to `us-west-2`

**Comment by adieuadieu** [comment]
Hi @Christilut — Hm.. weird. As far as I'm aware there's nothing that should keep it from working in `eu-central-1`. Have you tried another region, like `eu-west-1`? In other words, is it specifically _just_ `eu-central-1` which doesn't work?

**Comment by wim-jan** [comment]
@adieuadieu @Christilut I can confirm that it works on `eu-west-1`, but not on `eu-central-1`. Serverless responds with the error `The specified bucket does not exist`

**Comment by wim-jan** [comment]
@adieuadieu ok, I found the problem. Turns out that there was an existing CloudFormation that probably referenced removed buckets.
