### ISSUE TITLE
Question: How to process skipped images if lambda was paused for some time ?

### ISSUE THREAD

**Issue by mandeepm91** [adieuadieu/serverless-sharp-image#48]
This is not an issue but a question. Let's say I pause the lambda function and images keep coming on the source s3 bucket. Later on when I resume the lambda function, I not only want it to process newly added images but also the ones that were added when lambda function was not running. Is there any configuration that can accomplish this?

**Comment by adieuadieu** [comment]
Hi @mandeepm91 Hm.. The Lambda function is invoked for every object (image) when it's written to S3. There's no pausing the function. Each time an image is added to the source bucket, the Lambda function is executed.

**Comment by superandrew213** [comment]
@adieuadieu what if the region where the function is deployed is down?

**Comment by adieuadieu** [comment]
@superandrew213 Hm.. I don't know. I'm not sure what happens to events when the AWS Lambda service is down. Presumably the events are queued and processed once Lambda is operating normally again, but I don't know for sure—this isn't made clear by AWS.
